mongo:
  uri: mongodb://localhost:27017
  database: test
  ping: true
redis:
  uri: redis://localhost:6379
rabbitmq:
  uri: "amqp://admin:admin@localhost:5672"
  prefetchCount: 15
  queues:
    message:
      name: "im.message.send.queue"
      type: quorum
      durable: true
      consumers: 5
      ackOnSuccess: true
asynq:
  scheduler:
    zone: Asia/Shanghai
logger:
  level: INFO
  output: FILE
  path: ./logs
  age: 5
  backup: 3
  size: 4096